### ISSUE TITLE
刷新时页面header不回弹

### ISSUE THREAD

**Issue by zp-techie** [xuelongqy/flutter_easyrefresh#643]
刚进tab页面使用如下调用，发现header不回弹
Future.delayed(const Duration(milliseconds: 500), () {
      _controller.callRefresh();
    });

header使用的ClassicHeader

**Comment by xuelongqy** [comment]
可以试试引入github v3分支最新的代码

**Comment by zp-techie** [comment]
这种咋依赖呢，我看tag里面最新的是3.0.4&nbsp; &nbsp;大佬能整个最新的tag吗或者教教我怎么引用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuelongqy/flutter_easy_refresh"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xuelongqy/flutter_easy_refresh] 刷新时页面header不回弹 (Issue #643)





 
可以试试引入github v3分支最新的代码

**Comment by xuelongqy** [comment]
```yml
  flutter_easyrefresh:
    git:
      url: git://github.com/xuelongqy/flutter_easyrefresh.git
```
